"""
ContextEngine — Pulse v2
=========================
Multi-tier memory architecture for continuous cognitive state.

Tier architecture:
  HOT (48h)      Full fidelity JSONL. Every event. Rolling window, max 10,000 entries.
  WARM (30d)     Compressed day summaries. One entry per day. Generated by ThoughtLoop.
  COLD (all)     Semantic embeddings via FAISS/pgvector. Aged-out hot entries.
  RELATIONSHIP   Per-person JSON files. Never expire.

Day 2 implementation: Hot Tier (full) + stubs for warm/cold/relationship.
Day 3: Warm Tier + Relationship files.
Day 4: Cold Tier (embeddings).

See PULSE_V2_PHASE1_SPRINT.md for full spec.
"""

from __future__ import annotations

import json
import os
import threading
import time
from copy import deepcopy
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Any, Optional

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

HOT_TIER_MAX_ENTRIES = 10_000
HOT_TIER_MAX_AGE_HOURS = 48

# Valid event types logged to hot tier
EVENT_TYPES = {
    "MESSAGE_RECEIVED",
    "MESSAGE_SENT",
    "PULSE_TRIGGER",
    "THOUGHT_LOOP",
    "EMOTIONAL_SHIFT",
    "DRIVE_PEAK",
    "GOAL_PROGRESS",
    "SYSTEM_EVENT",
    "RELATIONSHIP_UPDATE",
    "INSIGHT",
}


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _now_ts() -> float:
    return time.time()


def _ts_from_iso(iso: str) -> float:
    """Convert ISO-8601 string to POSIX timestamp."""
    try:
        dt = datetime.fromisoformat(iso)
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt.timestamp()
    except (ValueError, TypeError):
        return 0.0


# ---------------------------------------------------------------------------
# HotTier — 48h rolling JSONL window
# ---------------------------------------------------------------------------


class HotTier:
    """
    Append-only JSONL file with a 48h rolling window.

    Thread-safe for concurrent append/read.
    Auto-prunes on load and when entry count exceeds max.
    """

    def __init__(self, filepath: Path):
        self.filepath = filepath
        self._lock = threading.RLock()
        self.filepath.parent.mkdir(parents=True, exist_ok=True)
        # Prune stale entries on startup
        self._prune()

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def append(self, event: dict) -> None:
        """
        Append one event to the hot tier.

        Required keys: type, content
        Auto-injected: ts (ISO-8601), ts_unix (float)

        Prunes oldest entries if count exceeds HOT_TIER_MAX_ENTRIES.
        """
        with self._lock:
            entry = self._normalize_event(event)
            with open(self.filepath, "a", encoding="utf-8") as f:
                f.write(json.dumps(entry) + "\n")
            # Enforce entry cap lazily (every 100 appends)
            if self._line_count() > HOT_TIER_MAX_ENTRIES:
                self._cap_entries()

    def get_recent(self, hours: int = 2) -> list[dict]:
        """
        Return all events within the last `hours` hours.
        Sorted oldest-first.
        """
        cutoff = _now_ts() - (hours * 3600)
        return self._load(since_ts=cutoff)

    def get_since(self, ts: float) -> list[dict]:
        """Return all events since a given POSIX timestamp."""
        return self._load(since_ts=ts)

    def get_by_type(self, event_type: str, hours: int = 24) -> list[dict]:
        """Filter hot tier by event type within the last N hours."""
        entries = self.get_recent(hours)
        return [e for e in entries if e.get("type") == event_type]

    def get_all(self) -> list[dict]:
        """Return all entries (up to HOT_TIER_MAX_ENTRIES, post-prune)."""
        return self._load(since_ts=None)

    def count(self) -> int:
        """Return current entry count."""
        return self._line_count()

    def clear(self) -> None:
        """Wipe the hot tier. Intended for tests."""
        with self._lock:
            if self.filepath.exists():
                self.filepath.unlink()

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _normalize_event(self, event: dict) -> dict:
        """Ensure all required fields are present."""
        entry = dict(event)
        if "ts" not in entry:
            entry["ts"] = _now_iso()
        if "ts_unix" not in entry:
            entry["ts_unix"] = _ts_from_iso(entry["ts"])
        if "type" not in entry:
            entry["type"] = "SYSTEM_EVENT"
        if "content" not in entry:
            entry["content"] = ""
        if "source" not in entry:
            entry["source"] = "pulse"
        return entry

    def _load(self, since_ts: Optional[float] = None) -> list[dict]:
        """Read JSONL file, return entries optionally filtered by timestamp."""
        entries: list[dict] = []
        if not self.filepath.exists():
            return entries
        with self._lock:
            try:
                with open(self.filepath, "r", encoding="utf-8") as f:
                    for line in f:
                        line = line.strip()
                        if not line:
                            continue
                        try:
                            entry = json.loads(line)
                            if since_ts is not None:
                                entry_ts = entry.get("ts_unix", 0.0)
                                if entry_ts < since_ts:
                                    continue
                            entries.append(entry)
                        except json.JSONDecodeError:
                            continue  # Skip malformed lines
            except OSError:
                return []
        return entries

    def _line_count(self) -> int:
        if not self.filepath.exists():
            return 0
        try:
            with open(self.filepath, "r", encoding="utf-8") as f:
                return sum(1 for line in f if line.strip())
        except OSError:
            return 0

    def _prune(self) -> None:
        """Remove entries older than HOT_TIER_MAX_AGE_HOURS."""
        with self._lock:
            cutoff = _now_ts() - (HOT_TIER_MAX_AGE_HOURS * 3600)
            self._rewrite_filtered(since_ts=cutoff)

    def _cap_entries(self) -> None:
        """Keep only the most recent HOT_TIER_MAX_ENTRIES entries."""
        with self._lock:
            all_entries = self._load(since_ts=None)
            if len(all_entries) <= HOT_TIER_MAX_ENTRIES:
                return
            keep = all_entries[-HOT_TIER_MAX_ENTRIES:]
            self._write_entries(keep)

    def _rewrite_filtered(self, since_ts: float) -> None:
        """Rewrite the file keeping only entries at or after since_ts."""
        entries = self._load(since_ts=since_ts)
        self._write_entries(entries)

    def _write_entries(self, entries: list[dict]) -> None:
        """Atomically rewrite the JSONL file with given entries."""
        tmp = self.filepath.with_suffix(".tmp")
        with open(tmp, "w", encoding="utf-8") as f:
            for entry in entries:
                f.write(json.dumps(entry) + "\n")
        os.replace(tmp, self.filepath)


# ---------------------------------------------------------------------------
# WarmTier — Day summaries (Day 3 implementation)
# ---------------------------------------------------------------------------


class WarmTier:
    """
    One summary per day. Generated by ThoughtLoop during off-peak hours.
    Day 3 implementation — full template-based compression.
    Local-model synthesis layer planned for Day 4 ThoughtLoop integration.
    """

    def __init__(self, filepath: Path):
        self.filepath = filepath
        self.filepath.parent.mkdir(parents=True, exist_ok=True)

    def get_day(self, date: str) -> Optional[dict]:
        """Retrieve summary for a specific date (YYYY-MM-DD). Returns None if absent."""
        if not self.filepath.exists():
            return None
        try:
            with open(self.filepath, "r", encoding="utf-8") as f:
                data = json.load(f)
            return data.get(date)
        except (OSError, json.JSONDecodeError):
            return None

    def get_recent_days(self, n: int = 7) -> list[dict]:
        """Return up to N most recent day summaries."""
        if not self.filepath.exists():
            return []
        try:
            with open(self.filepath, "r", encoding="utf-8") as f:
                data = json.load(f)
            sorted_days = sorted(data.items(), key=lambda x: x[0], reverse=True)
            return [v for _, v in sorted_days[:n]]
        except (OSError, json.JSONDecodeError):
            return []

    def write_day(self, date: str, summary: dict) -> None:
        """Write or overwrite a day summary. Called by ThoughtLoop."""
        data: dict = {}
        if self.filepath.exists():
            try:
                with open(self.filepath, "r", encoding="utf-8") as f:
                    data = json.load(f)
            except (OSError, json.JSONDecodeError):
                data = {}
        data[date] = summary
        tmp = self.filepath.with_suffix(".tmp")
        with open(tmp, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)
        os.replace(tmp, self.filepath)

    def delete_day(self, date: str) -> bool:
        """Remove a day summary. Returns True if it existed."""
        if not self.filepath.exists():
            return False
        try:
            with open(self.filepath, "r", encoding="utf-8") as f:
                data = json.load(f)
        except (OSError, json.JSONDecodeError):
            return False
        if date not in data:
            return False
        del data[date]
        tmp = self.filepath.with_suffix(".tmp")
        with open(tmp, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)
        os.replace(tmp, self.filepath)
        return True

    def list_dates(self) -> list[str]:
        """Return all dates with warm summaries, sorted newest-first."""
        if not self.filepath.exists():
            return []
        try:
            with open(self.filepath, "r", encoding="utf-8") as f:
                data = json.load(f)
            return sorted(data.keys(), reverse=True)
        except (OSError, json.JSONDecodeError):
            return []

    def compress_day(self, date: str, hot_entries: list[dict]) -> dict:
        """
        Build a warm summary from a list of hot entries.
        Day 3: full template-based extraction (no LLM required).
        Local-model synthesis will layer on top in Day 4 (ThoughtLoop).

        Extracted fields:
          themes          — unique event types present
          emotional_arc   — derived from EMOTIONAL_SHIFT events
          key_events      — top events by priority (non-system first)
          projects_touched — extracted from PULSE_TRIGGER content
          mood_avg        — derived from endocrine/drive data where available
          drive_peaks     — drives that fired during the day
          message_count   — total MESSAGE_RECEIVED + MESSAGE_SENT
          pulse_triggers  — count of PULSE_TRIGGER events
        """
        if not hot_entries:
            return {
                "date": date,
                "event_count": 0,
                "themes": [],
                "emotional_arc": "quiet",
                "key_events": [],
                "projects_touched": [],
                "mood_avg": 0.5,
                "drive_peaks": [],
                "message_count": 0,
                "pulse_triggers": 0,
                "generated_at": _now_iso(),
                "generated_by": "template_v1",
            }

        # --- Themes: unique event types ---
        themes: list[str] = sorted(
            {e.get("type", "SYSTEM_EVENT") for e in hot_entries}
        )

        # --- Emotional arc: derived from EMOTIONAL_SHIFT transitions ---
        shifts = [
            e for e in hot_entries if e.get("type") == "EMOTIONAL_SHIFT"
        ]
        if shifts:
            # Arc: first_state → last_state (compressed)
            first = shifts[0].get("from_state", "")
            last = shifts[-1].get("to_state", "")
            if first and last and first != last:
                emotional_arc = f"{first} → {last}"
            elif last:
                emotional_arc = last
            elif first:
                emotional_arc = first
            else:
                emotional_arc = "shifting"
        elif any(e.get("type") == "EMOTIONAL_SHIFT" for e in hot_entries):
            emotional_arc = "active"
        else:
            # Infer from event mix
            type_counts: dict[str, int] = {}
            for e in hot_entries:
                t = e.get("type", "")
                type_counts[t] = type_counts.get(t, 0) + 1
            if type_counts.get("PULSE_TRIGGER", 0) > 5:
                emotional_arc = "driven"
            elif type_counts.get("MESSAGE_RECEIVED", 0) > 3:
                emotional_arc = "connected"
            elif type_counts.get("GOAL_PROGRESS", 0) > 0:
                emotional_arc = "progressing"
            elif type_counts.get("INSIGHT", 0) > 0:
                emotional_arc = "reflective"
            else:
                emotional_arc = "neutral"

        # --- Key events: top 5, non-system preferred ---
        priority_types = {
            "GOAL_PROGRESS": 5,
            "INSIGHT": 4,
            "EMOTIONAL_SHIFT": 3,
            "PULSE_TRIGGER": 2,
            "MESSAGE_RECEIVED": 2,
            "MESSAGE_SENT": 2,
            "RELATIONSHIP_UPDATE": 3,
            "THOUGHT_LOOP": 1,
            "DRIVE_PEAK": 1,
            "SYSTEM_EVENT": 0,
        }
        scored_entries = sorted(
            hot_entries,
            key=lambda e: (
                priority_types.get(e.get("type", ""), 0),
                e.get("ts_unix", 0.0),
            ),
            reverse=True,
        )
        key_events: list[str] = []
        seen_snippets: set[str] = set()
        for e in scored_entries:
            content = str(e.get("content", "")).strip()
            if not content:
                continue
            snippet = content[:140]
            if snippet in seen_snippets:
                continue
            seen_snippets.add(snippet)
            key_events.append(snippet)
            if len(key_events) >= 5:
                break

        # --- Projects touched: extracted from PULSE_TRIGGER content ---
        project_keywords = [
            "anima", "gnosis", "weather", "sdca", "pulse", "invoiceflow",
            "cpi", "hypostas", "locus", "aether", "bios", "3d internet",
            "local-model", "constellation", "context_engine", "state_engine",
            "thought_loop", "runtime_bridge",
        ]
        projects_found: set[str] = set()
        for e in hot_entries:
            content_lower = str(e.get("content", "")).lower()
            for proj in project_keywords:
                if proj in content_lower:
                    projects_found.add(proj)
        projects_touched = sorted(projects_found)

        # --- Drive peaks: drives that fired (from DRIVE_PEAK events) ---
        drive_peaks: list[str] = []
        for e in hot_entries:
            if e.get("type") == "DRIVE_PEAK":
                drive = e.get("drive", e.get("content", ""))
                if drive and drive not in drive_peaks:
                    drive_peaks.append(drive)
        # Also extract from PULSE_TRIGGER drive field
        for e in hot_entries:
            if e.get("type") == "PULSE_TRIGGER":
                drive = e.get("drive", "")
                if drive and drive not in drive_peaks:
                    drive_peaks.append(drive)

        # --- Mood average: derived from endocrine fields where available ---
        valence_samples: list[float] = []
        for e in hot_entries:
            # Look for valence in event metadata
            valence = e.get("valence")
            if valence is not None:
                try:
                    valence_samples.append(float(valence))
                except (TypeError, ValueError):
                    pass
            # Infer from endocrine if present
            endocrine = e.get("endocrine", {})
            if endocrine:
                dopamine = endocrine.get("dopamine", 0.0)
                oxytocin = endocrine.get("oxytocin", 0.0)
                cortisol = endocrine.get("cortisol", 0.0)
                if dopamine or oxytocin or cortisol:
                    # Simple positive bias formula: (dopa + oxt - cortisol/2) / 20
                    sample = (
                        (dopamine + oxytocin - cortisol * 0.5) / 20.0
                    )
                    valence_samples.append(max(0.0, min(1.0, sample)))
        mood_avg = (
            round(sum(valence_samples) / len(valence_samples), 3)
            if valence_samples
            else 0.5
        )

        # --- Message and trigger counts ---
        message_count = sum(
            1
            for e in hot_entries
            if e.get("type") in ("MESSAGE_RECEIVED", "MESSAGE_SENT")
        )
        pulse_trigger_count = sum(
            1 for e in hot_entries if e.get("type") == "PULSE_TRIGGER"
        )

        return {
            "date": date,
            "event_count": len(hot_entries),
            "themes": themes,
            "emotional_arc": emotional_arc,
            "key_events": key_events,
            "projects_touched": projects_touched,
            "mood_avg": mood_avg,
            "drive_peaks": drive_peaks,
            "message_count": message_count,
            "pulse_triggers": pulse_trigger_count,
            "generated_at": _now_iso(),
            "generated_by": "template_v1",
        }


# ---------------------------------------------------------------------------
# RelationshipTier — per-person JSON files (Day 3 implementation)
# ---------------------------------------------------------------------------


class RelationshipTier:
    """
    Per-person JSON files in `relationships/` subdirectory.
    Never expire. Track: last seen, conversation threads, bond strength.
    Day 3 full implementation — basic CRUD here.
    """

    def __init__(self, directory: Path):
        self.directory = directory
        self.directory.mkdir(parents=True, exist_ok=True)

    def _person_file(self, person: str) -> Path:
        safe = person.lower().replace(" ", "_").replace("/", "_")
        return self.directory / f"{safe}.json"

    def get(self, person: str) -> dict:
        """Return relationship data for a person. Empty dict if unknown."""
        path = self._person_file(person)
        if not path.exists():
            return {}
        try:
            with open(path, "r", encoding="utf-8") as f:
                return json.load(f)
        except (OSError, json.JSONDecodeError):
            return {}

    def update(self, person: str, event: dict) -> None:
        """
        Merge an event into a person's relationship file.
        Creates the file if it doesn't exist.
        """
        touch = event.get("_touch", True) is not False

        data = self.get(person)
        if not data:
            # Allow callers to seed first_seen/last_seen on first creation.
            seeded_first = event.get("first_seen") or _now_iso()
            seeded_last = event.get("last_seen") or _now_iso()
            data = {
                "person": person,
                "first_seen": seeded_first,
                "last_seen": seeded_last,
                "interaction_count": 0,
                "bond_strength": 0.5,
                "notes": [],
                "recent_themes": [],
            }

        if touch:
            data["last_seen"] = _now_iso()
            data["interaction_count"] = data.get("interaction_count", 0) + 1
        else:
            # Non-touch update (e.g. decay sweep). Preserve last_seen + interaction_count.
            if "last_seen" in event:
                data["last_seen"] = event["last_seen"]
            if "first_seen" in event and "first_seen" not in data:
                data["first_seen"] = event["first_seen"]
        # Append note if provided
        note = event.get("note")
        if note:
            notes: list = data.get("notes", [])
            notes.append({"ts": _now_iso(), "content": note})
            # Keep last 50 notes
            data["notes"] = notes[-50:]
        # Merge extra fields from event
        # NOTE: Some fields are intentionally mutable (bond strength, themes, threads).
        mutable_fields = {
            "bond_strength",
            "recent_themes",
            "active_threads",
            "current_context",
            "what_he_needs_right_now",
            "tier",
            "kind",
        }
        for k, v in event.items():
            if k in ("note", "ts", "ts_unix", "first_seen", "last_seen"):
                continue
            # Internal control keys (do not persist)
            if k.startswith("_"):
                continue
            if k in mutable_fields:
                # Special merge for recent_themes
                if k == "recent_themes" and isinstance(v, list):
                    existing = list(data.get("recent_themes") or [])
                    for t in v:
                        t = str(t).strip()
                        if not t:
                            continue
                        if t in existing:
                            existing.remove(t)
                        existing.append(t)
                    data["recent_themes"] = existing[-20:]
                else:
                    data[k] = v
            else:
                # Non-mutable fields: only set if missing (preserve history)
                if k not in data:
                    data[k] = v
        path = self._person_file(person)
        tmp = path.with_suffix(".tmp")
        with open(tmp, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)
        os.replace(tmp, path)

    def get_all(self) -> dict[str, dict]:
        """Return all relationship files as {person: data}."""
        result: dict[str, dict] = {}
        for path in sorted(self.directory.glob("*.json")):
            try:
                with open(path, "r", encoding="utf-8") as f:
                    data = json.load(f)
                result[data.get("person", path.stem)] = data
            except (OSError, json.JSONDecodeError):
                continue
        return result

    def list_people(self) -> list[str]:
        """Return list of known person names."""
        result = []
        for path in sorted(self.directory.glob("*.json")):
            try:
                with open(path, "r", encoding="utf-8") as f:
                    data = json.load(f)
                result.append(data.get("person", path.stem))
            except (OSError, json.JSONDecodeError):
                result.append(path.stem.replace("_", " "))
        return result

    def seed(self, person: str, seed_data: dict, overwrite: bool = False) -> bool:
        """
        Seed a relationship file with pre-populated data.
        Used at startup to pre-load known context from SOUL.md / USER.md.

        Returns True if file was written, False if it already existed and
        overwrite=False.
        """
        path = self._person_file(person)
        if path.exists() and not overwrite:
            return False
        data = {
            "person": person,
            "first_seen": seed_data.get("first_seen", _now_iso()),
            "last_seen": seed_data.get("last_seen", _now_iso()),
            "interaction_count": seed_data.get("interaction_count", 0),
            "bond_strength": seed_data.get("bond_strength", 0.5),
            "notes": seed_data.get("notes", []),
            "recent_themes": seed_data.get("recent_themes", []),
            "seeded_at": _now_iso(),
            "seeded_from": seed_data.get("seeded_from", "manual"),
            **{
                k: v
                for k, v in seed_data.items()
                if k
                not in (
                    "person",
                    "first_seen",
                    "last_seen",
                    "interaction_count",
                    "bond_strength",
                    "notes",
                    "recent_themes",
                    "seeded_at",
                    "seeded_from",
                )
            },
        }
        tmp = path.with_suffix(".tmp")
        with open(tmp, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)
        os.replace(tmp, path)
        return True

    def delete(self, person: str) -> bool:
        """Remove a relationship file. Returns True if it existed."""
        path = self._person_file(person)
        if not path.exists():
            return False
        path.unlink()
        return True


# ---------------------------------------------------------------------------
# ColdTier — semantic embeddings (Day 4 stub)
# ---------------------------------------------------------------------------


class ColdTier:
    """
    Cold-tier archive for aged-out hot entries.

    Uses JSONL archive files with a keyword-search index.
    No FAISS required — pure stdlib fallback that always works.
    Files: cold-tier/archive-<ts>.jsonl + cold-tier/index.json

    FAISS semantic search is attempted as an optional upgrade but
    the tier is fully functional without it.
    """

    def __init__(self, index_dir: Path):
        self.index_dir = index_dir
        self.index_dir.mkdir(parents=True, exist_ok=True)
        self._index_path = index_dir / "index.json"
        self._lock = threading.RLock()
        self._total: int = 0
        self._load_index()

    # ------------------------------------------------------------------
    # Index management
    # ------------------------------------------------------------------

    def _load_index(self) -> None:
        """Load or initialise the index.json catalog."""
        with self._lock:
            if self._index_path.exists():
                try:
                    data = json.loads(self._index_path.read_text("utf-8"))
                    self._total = int(data.get("total", 0))
                except Exception:
                    self._total = 0
            else:
                self._total = 0
                self._save_index_locked()

    def _save_index_locked(self) -> None:
        """Persist index.json. Caller must hold self._lock."""
        try:
            # List archive files for the catalog
            archives = sorted(self.index_dir.glob("archive-*.jsonl"))
            catalog = [
                {"file": a.name, "size_bytes": a.stat().st_size}
                for a in archives
            ]
            data = {
                "total": self._total,
                "archives": catalog,
                "updated_at": datetime.now(timezone.utc).isoformat(),
            }
            tmp = self._index_path.with_suffix(".tmp")
            tmp.write_text(json.dumps(data, indent=2), encoding="utf-8")
            os.replace(tmp, self._index_path)
        except Exception:
            pass  # non-fatal

    # ------------------------------------------------------------------
    # Archive path (one file per UTC day)
    # ------------------------------------------------------------------

    def _archive_path(self, ts: Optional[float] = None) -> Path:
        """Return the archive JSONL path for a given epoch timestamp."""
        ts = ts or time.time()
        date_str = datetime.fromtimestamp(ts, tz=timezone.utc).strftime("%Y-%m-%d")
        return self.index_dir / f"archive-{date_str}.jsonl"

    # ------------------------------------------------------------------
    # Encode (replace FAISS.encode)
    # ------------------------------------------------------------------

    def encode(self, entries: list[dict]) -> int:
        """
        Archive hot-tier entries to cold storage.
        Returns the number of entries successfully archived.
        """
        if not entries:
            return 0

        # Group entries by date to write into the correct archive file
        by_date: dict[str, list[dict]] = {}
        for e in entries:
            content = str(e.get("content", "")).strip()
            if not content or len(content) < 5:
                continue
            ts_unix = float(e.get("ts_unix", 0.0) or 0.0)
            if ts_unix <= 0.0:
                ts_unix = time.time()
            date_key = datetime.fromtimestamp(ts_unix, tz=timezone.utc).strftime("%Y-%m-%d")
            record = {
                "type": e.get("type", "SYSTEM_EVENT"),
                "content": content[:500],
                "source": e.get("source", ""),
                "ts": e.get("ts", ""),
                "ts_unix": ts_unix,
            }
            by_date.setdefault(date_key, []).append(record)

        written = 0
        with self._lock:
            for date_key, records in by_date.items():
                archive_path = self.index_dir / f"archive-{date_key}.jsonl"
                try:
                    with archive_path.open("a", encoding="utf-8") as f:
                        for rec in records:
                            f.write(json.dumps(rec, ensure_ascii=False) + "\n")
                    written += len(records)
                except OSError:
                    pass
            self._total += written
            if written:
                self._save_index_locked()

        return written

    # ------------------------------------------------------------------
    # Search (keyword fallback — no FAISS required)
    # ------------------------------------------------------------------

    def search(self, query: str, top_k: int = 5) -> list[dict]:
        """
        Search cold-tier archives by keyword matching.

        Scores each entry by number of query terms found (case-insensitive).
        Returns top_k results sorted by score (descending), then recency.
        Falls back to FAISS if available (best-effort upgrade).
        """
        if not query or not query.strip():
            return []

        terms = [t.lower() for t in query.split() if len(t) >= 3]
        if not terms:
            return []

        results: list[tuple[int, float, dict]] = []  # (score, ts_unix, record)

        with self._lock:
            archives = sorted(self.index_dir.glob("archive-*.jsonl"), reverse=True)

        # Scan up to the 10 most recent archives
        for archive_path in archives[:10]:
            try:
                lines = archive_path.read_text("utf-8").splitlines()
            except OSError:
                continue
            for line in lines:
                line = line.strip()
                if not line:
                    continue
                try:
                    rec = json.loads(line)
                except json.JSONDecodeError:
                    continue
                text = (str(rec.get("content", "")) + " " + str(rec.get("type", ""))).lower()
                score = sum(1 for t in terms if t in text)
                if score > 0:
                    results.append((score, float(rec.get("ts_unix", 0.0)), rec))

        # Sort by score DESC, then recency DESC
        results.sort(key=lambda x: (x[0], x[1]), reverse=True)
        out = []
        for score, ts_unix, rec in results[:top_k]:
            r = dict(rec)
            r["score"] = float(score) / max(1, len(terms))
            out.append(r)
        return out

    def count(self) -> int:
        # Read index.json each call so external writers (e.g., EpisodicBuffer eviction)
        # are reflected without requiring a runtime restart.
        with self._lock:
            try:
                if self._index_path.exists():
                    data = json.loads(self._index_path.read_text("utf-8"))
                    self._total = int(data.get("total", self._total))
            except Exception:
                pass
            return self._total


# ---------------------------------------------------------------------------
# ContextEngine — top-level coordinator
# ---------------------------------------------------------------------------


class ContextEngine:
    """
    Multi-tier memory engine for Pulse v2.

    Tiers:
      hot          — last 48h, full fidelity JSONL (LIVE)
      warm         — day summaries, 30d retention (Day 3)
      cold         — semantic index, unbounded (Day 4)
      relationship — per-person persistent files (Day 3)

    Usage:
        engine = ContextEngine(Path("~/.pulse/state").expanduser())
        engine.log_event({"type": "MESSAGE_RECEIVED", "content": "...", "source": "Josh"})
        recent = engine.get_recent_context(hours=2)
        ctx = engine.get_project_context("weather-bot")
    """

    def __init__(self, state_dir: Optional[Path] = None):
        if state_dir is None:
            state_dir = Path("~/.pulse/state").expanduser()
        self.state_dir = Path(state_dir)
        self.state_dir.mkdir(parents=True, exist_ok=True)

        self.hot = HotTier(self.state_dir / "context-hot.jsonl")
        self.warm = WarmTier(self.state_dir / "context-warm.json")
        self.cold = ColdTier(self.state_dir / "cold-tier")
        self.relationship = RelationshipTier(self.state_dir / "relationships")

    # ------------------------------------------------------------------
    # Core event logging
    # ------------------------------------------------------------------

    def log_event(self, event: dict) -> None:
        """
        Append an event to the hot tier.

        Minimum required: {type, content}
        Optional: source, metadata (any extra keys)

        Example:
            engine.log_event({
                "type": "MESSAGE_RECEIVED",
                "content": "Hey Iris, how's the weather bot doing?",
                "source": "Josh",
            })
        """
        if event.get("type") not in EVENT_TYPES:
            event = dict(event)
            event["type"] = "SYSTEM_EVENT"
        self.hot.append(event)

    def log_pulse_trigger(self, drive: str, pressure: float, summary: str) -> None:
        """Convenience: log a Pulse trigger event."""
        self.log_event(
            {
                "type": "PULSE_TRIGGER",
                "content": summary,
                "source": "pulse",
                "drive": drive,
                "pressure": pressure,
            }
        )

    def log_message(
        self, direction: str, content: str, source: str = "unknown"
    ) -> None:
        """
        Convenience: log an incoming or outgoing message.
        direction: "received" | "sent"
        """
        event_type = (
            "MESSAGE_RECEIVED" if direction == "received" else "MESSAGE_SENT"
        )
        self.log_event({"type": event_type, "content": content, "source": source})

    def log_insight(self, content: str, source: str = "thought_loop") -> None:
        """Log a generated insight."""
        self.log_event({"type": "INSIGHT", "content": content, "source": source})

    def log_emotional_shift(
        self, from_state: str, to_state: str, trigger: str = ""
    ) -> None:
        """Log a significant emotional state change."""
        self.log_event(
            {
                "type": "EMOTIONAL_SHIFT",
                "content": f"{from_state} → {to_state}",
                "source": "emotional_engine",
                "from_state": from_state,
                "to_state": to_state,
                "trigger": trigger,
            }
        )

    # ------------------------------------------------------------------
    # Retrieval
    # ------------------------------------------------------------------

    def get_recent_context(self, hours: int = 2) -> list[dict]:
        """
        Pull from hot tier. Used for ThoughtLoop continuity.
        Returns events sorted oldest-first.
        """
        return self.hot.get_recent(hours=hours)

    def get_project_context(self, project: str) -> dict:
        """
        Cross-tier context for a project.
        Hot for recent activity, warm for arc, cold for history.
        """
        recent = [
            e
            for e in self.hot.get_recent(hours=72)
            if project.lower() in str(e.get("content", "")).lower()
            or project.lower() in str(e.get("metadata", "")).lower()
        ]
        warm_recent = self.warm.get_recent_days(7)
        return {
            "project": project,
            "recent_events": recent[-20:],  # Last 20 matching hot entries
            "warm_arc": warm_recent,
            "cold_hits": self.cold.search(project, top_k=5),
        }

    def get_events_by_type(self, event_type: str, hours: int = 24) -> list[dict]:
        """Filter hot tier by event type."""
        return self.hot.get_by_type(event_type, hours=hours)

    # ------------------------------------------------------------------
    # Relationship management
    # ------------------------------------------------------------------

    def get_relationship(self, person: str) -> dict:
        """Always-fresh relationship context for a person."""
        return self.relationship.get(person)

    def update_relationship(self, person: str, event: dict) -> None:
        """Called after every meaningful interaction with a person."""
        self.relationship.update(person, event)

        # Also log to hot tier (unless suppressed)
        if event.get("_log", True) is False:
            return

        self.log_event(
            {
                "type": "RELATIONSHIP_UPDATE",
                "content": f"Interaction with {person}",
                "source": "context_engine",
                "person": person,
                **{k: v for k, v in event.items() if k != "note" and not str(k).startswith("_")},
            }
        )

    def get_all_relationships(self) -> dict[str, dict]:
        """Return all relationship data."""
        return self.relationship.get_all()

    # ------------------------------------------------------------------
    # Compression (Day 3 — warm tier generation)
    # ------------------------------------------------------------------

    def compress_to_warm(self, date: Optional[str] = None) -> dict:
        """
        Summarize a day's hot entries into the warm tier.
        Called by ThoughtLoop. Full local-model synthesis in Day 3.
        """
        if date is None:
            date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        # Get entries for that date
        start_of_day = datetime.strptime(date, "%Y-%m-%d").replace(
            tzinfo=timezone.utc
        )
        end_of_day = start_of_day + timedelta(days=1)
        all_entries = self.hot.get_all()
        day_entries = [
            e
            for e in all_entries
            if start_of_day.timestamp()
            <= e.get("ts_unix", 0.0)
            < end_of_day.timestamp()
        ]
        summary = self.warm.compress_day(date, day_entries)
        self.warm.write_day(date, summary)
        return summary

    def encode_to_cold(self, entries: list[dict]) -> int:
        """Move aged-out hot entries into semantic embedding store."""
        return self.cold.encode(entries)

    # ------------------------------------------------------------------
    # Status
    # ------------------------------------------------------------------

    def status(self) -> dict:
        """Return quick status snapshot."""
        return {
            "hot_entries": self.hot.count(),
            "hot_max_age_hours": HOT_TIER_MAX_AGE_HOURS,
            "hot_max_entries": HOT_TIER_MAX_ENTRIES,
            "warm_days": len(self.warm.get_recent_days(30)),
            "cold_entries": self.cold.count(),
            "known_people": self.relationship.list_people(),
        }
