"""
REM — Dreaming Engine (PONS)
================================
Ported from v1 pulse.src.rem into v2 HypostasRuntime.

Structured imagination during quiet periods. Replays memories,
branches hypotheticals, finds cross-domain patterns, produces
creative output.

Safety invariant: ZERO external actions during REM sessions.
Only internal state writes.

All state persisted via StateEngine under ``rem.*`` dot-paths.
"""

from __future__ import annotations

import time
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, Any, Dict, List, Optional

if TYPE_CHECKING:
    from .state_engine import StateEngine
    from .context_engine import ContextEngine
    from .self_model import SelfModel

# Configuration
STILLNESS_THRESHOLD = 2.0
SUSTAINED_MINUTES = 30
MAX_DURATION_SECONDS = 300
MEMORY_REPLAY_COUNT = 5
HYPOTHETICAL_BRANCHES = 3
DREAM_LOG_DIR = Path("~/.pulse/state/dreams").expanduser()


class Rem:
    """Dreaming engine — structured imagination during quiet periods."""

    _KEY = "rem"

    def __init__(
        self,
        state: "StateEngine",
        context: "ContextEngine",
        self_model: "SelfModel",
    ) -> None:
        self._state = state
        self._context = context
        self._self_model = self_model
        self._active = False  # Safety guard

        if self._state.get(f"{self._KEY}.total_sessions") is None:
            self._state.set(f"{self._KEY}.total_sessions", 0)
            self._state.set(f"{self._KEY}.last_session_ts", 0)
            self._state.set(f"{self._KEY}.themes_explored", [])
            self._state.set(f"{self._KEY}.creative_outputs", 0)
            self._state.set(f"{self._KEY}.last_session", None)

    @property
    def is_active(self) -> bool:
        """Returns True if a REM session is in progress (safety guard)."""
        return self._active

    def check_action(self, action_name: str = "unknown") -> bool:
        """Returns True if action is allowed. False if REM is active."""
        if self._active:
            return False
        return True

    def eligible(self, drives: Optional[Dict[str, Any]] = None, force: bool = False) -> tuple:
        """Check if REM should activate.

        Returns (eligible: bool, reason: str).
        """
        if force:
            return True, "forced"

        if drives is None:
            drives = self._state.get("drives") or {}

        for name, value in drives.items():
            pressure = value if isinstance(value, (int, float)) else 0
            if hasattr(value, "pressure"):
                pressure = value.pressure
            elif isinstance(value, dict):
                pressure = value.get("pressure", 0)
            if pressure >= STILLNESS_THRESHOLD:
                return False, f"drive '{name}' pressure {pressure:.2f} >= threshold"

        return True, "all drives quiet"

    def run_session(self, force: bool = False) -> Optional[dict]:
        """Run a full dreaming session.

        Returns session dict or None if not eligible.
        """
        eligible, reason = self.eligible(force=force)
        if not eligible:
            return None

        self._active = True
        session_start = time.time()

        try:
            # Phase 1 — Memory Replay
            fragments = self._load_replay_fragments()

            # Phase 2 — Hypothetical Branching
            hypotheticals = []
            if fragments:
                top = max(fragments, key=lambda f: f.get("weight", 0))
                for i in range(HYPOTHETICAL_BRANCHES):
                    hypotheticals.append(
                        f"[Branch {i+1} from: {top.get('content', '')[:80]}...]"
                    )

            # Phase 3 — Pattern Synthesis
            patterns = []
            if len(fragments) >= 2:
                sources = [f.get("source", "unknown") for f in fragments[:3]]
                patterns.append(f"[Cross-pattern across: {', '.join(sources)}]")

            # Phase 4 — Creative Output (placeholder for LLM fill)
            creative_type = "insight"
            creative_output = "[Creative output to be generated by agent context]"

            # Extract themes
            themes = list(set(
                tag for f in fragments for tag in f.get("tags", [])
            ))[:10]

            session_end = time.time()

            session = {
                "started_at": session_start,
                "ended_at": session_end,
                "duration_seconds": round(session_end - session_start, 1),
                "replay_count": len(fragments),
                "hypothetical_count": len(hypotheticals),
                "pattern_count": len(patterns),
                "creative_type": creative_type,
                "themes": themes,
            }

            # Update state
            total = int(self._state.get(f"{self._KEY}.total_sessions") or 0) + 1
            self._state.set(f"{self._KEY}.total_sessions", total)
            self._state.set(f"{self._KEY}.last_session_ts", session_end)
            self._state.set(f"{self._KEY}.last_session", session)

            if creative_output:
                count = int(self._state.get(f"{self._KEY}.creative_outputs") or 0) + 1
                self._state.set(f"{self._KEY}.creative_outputs", count)

            # Track themes
            explored = list(self._state.get(f"{self._KEY}.themes_explored") or [])
            for t in themes:
                if t not in explored:
                    explored.append(t)
            self._state.set(f"{self._KEY}.themes_explored", explored[-50:])

            # Write dream log
            self._write_dream_log(session, fragments, hypotheticals, patterns)

            return session

        finally:
            self._active = False

    def _load_replay_fragments(self) -> List[dict]:
        """Pull recent memories weighted by emotional intensity."""
        fragments = []

        try:
            recent = self._context.get_recent_context(hours=168)  # 7 days
            for event in (recent or [])[-20:]:
                content = event.get("content", "")
                if isinstance(content, dict):
                    content = content.get("summary", str(content))
                content = str(content)[:500]
                if len(content.strip()) < 20:
                    continue

                fragments.append({
                    "source": event.get("type", "unknown"),
                    "content": content,
                    "weight": float(event.get("salience", 0.3)),
                    "tags": [],
                })
        except Exception:
            pass

        fragments.sort(key=lambda f: f.get("weight", 0), reverse=True)
        return fragments[:MEMORY_REPLAY_COUNT]

    def _write_dream_log(
        self,
        session: dict,
        fragments: list,
        hypotheticals: list,
        patterns: list,
    ) -> None:
        """Write dream session to state for persistence."""
        log = list(self._state.get(f"{self._KEY}.dream_log") or [])
        log.append({
            "ts": session["started_at"],
            "duration": session["duration_seconds"],
            "fragments": len(fragments),
            "hypotheticals": len(hypotheticals),
            "patterns": len(patterns),
            "themes": session.get("themes", []),
        })
        self._state.set(f"{self._KEY}.dream_log", log[-50:])

    def tick(self) -> None:
        """No-op — REM is triggered by ThoughtLoop during dream hours."""
        pass

    def status(self) -> dict:
        return {
            "total_sessions": int(self._state.get(f"{self._KEY}.total_sessions") or 0),
            "last_session_ts": self._state.get(f"{self._KEY}.last_session_ts"),
            "creative_outputs": int(self._state.get(f"{self._KEY}.creative_outputs") or 0),
            "themes_explored": len(self._state.get(f"{self._KEY}.themes_explored") or []),
            "active": self._active,
        }
